import { Book } from '../model/book';
import { BookType } from '../model/book-types';
import { USERS } from '../fake-database/user-list';

export const BOOKS: Book[] = [
    {
        isbn: 1234567890123,
        title: 'Robinson Crusoe',
        author: 'Daniel Defoe',
        type: BookType.Adventure,
        pagesNumber: 342,
        releaseDate: new Date(2005, 11, 27),
        borrower: USERS[1].name,
    },
    {
        isbn: 3456789012312,
        title: 'Frankenstein',
        author: 'Mary Shelley',
        type: BookType.Horror,
        pagesNumber: 232,
        releaseDate: new Date(1995, 11, 17),
        borrower: '',
    },
    {
        isbn: 5477887586745,
        title: 'Hamlet',
        author: 'William Shakespeare',
        type: BookType.Romance,
        pagesNumber: 276,
        releaseDate: new Date(1999, 7, 24),
        borrower: USERS[3].name,
    },
    {
        isbn: 2334887342431,
        title: 'The Lord of the Rings',
        author: 'J. R. R. Tolkien',
        type: BookType.Fantasy,
        pagesNumber: 219,
        releaseDate: new Date(2001, 1, 30),
        borrower: '',
    },
    {
        isbn: 3245326542341,
        title: 'Gulliver’s Travels',
        author: 'Jonathan Swift',
        type: BookType.Adventure,
        pagesNumber: 329,
        releaseDate: new Date(1994, 9, 18),
        borrower: USERS[4].name,
    },
    {
        isbn: 6765754323312,
        title: 'Pride and Prejudice',
        author: 'Jane Austen',
        type: BookType.Romance,
        pagesNumber: 178,
        releaseDate: new Date(1998, 3, 30),
        borrower: '',
    },
    {
        isbn: 2345234523451,
        title: 'Forest One',
        author: 'Oliver Petit',
        type: BookType.Romance,
        pagesNumber: 348,
        releaseDate: new Date(1995, 7, 7),
        borrower: '',
    },
    {
        isbn: 432134343331,
        title: 'Forest Two',
        author: 'Eliv Alan',
        type: BookType.Adventure,
        pagesNumber: 348,
        releaseDate: new Date(1999, 4, 30),
        borrower: USERS[3].name,
    },
    {
        isbn: 6341586878312,
        title: 'Fast cars',
        author: 'Edward Oven',
        type: BookType.Romance,
        pagesNumber: 348,
        releaseDate: new Date(2009, 4, 30),
        borrower: '',
    },
    {
        isbn: 543639356693,
        title: 'FFootbal',
        author: 'Marcus Foot',
        type: BookType.Adventure,
        pagesNumber: 213,
        releaseDate: new Date(2019, 11, 22),
        borrower: USERS[1].name,
    },
    {
        isbn: 6523235234523,
        title: 'Bird in soup',
        author: 'Oliver Mcdonald',
        type: BookType.Fantasy,
        pagesNumber: 268,
        releaseDate: new Date(2008, 11, 11),
        borrower: '',
    },
    {
        isbn: 5623453095234,
        title: 'Bird in maroco',
        author: 'Stephan Gray',
        type: BookType.Romance,
        pagesNumber: 268,
        releaseDate: new Date(2011, 5, 5),
        borrower: '',
    },
    {
        isbn: 2345234523452,
        title: 'Walk with you',
        author: 'Ernest Puttinf',
        type: BookType.Fantasy,
        pagesNumber: 118,
        releaseDate: new Date(1994, 6, 12),
        borrower: '',
    },
    {
        isbn: 1248234523452,
        title: 'World war',
        author: 'Borys Povetkin',
        type: BookType.Horror,
        pagesNumber: 238,
        releaseDate: new Date(2007, 9, 11),
        borrower: USERS[4].name,
    },
    {
        isbn: 8875234523452,
        title: 'Hello fro hell',
        author: 'Arch Maserano',
        type: BookType.Horror,
        pagesNumber: 411,
        releaseDate: new Date(2010, 11, 2),
        borrower: USERS[0].name,
    }
];
